### ISSUE TITLE
How is the training going?

### ISSUE THREAD

**Issue by JiatianWu** [Yvette1993/fast-depth#1]
Hi, I am trying to recover the training code. I notice you are implementing it, can you share how is it going? Thanks.

**Comment by Yvette1993** [comment]
You can follow the README, download the data set and code. and then you can input "python main.py --help" see the detail.

**Comment by JiatianWu** [comment]
Awesome. Did you get similar results with the original paper?

**Comment by Yvette1993** [comment]
If you use the pre-weights will be get same results.
